package Layout.Cad;

import User.Cad;
import Layout.F_Login;
import javax.swing.JOptionPane;

/**
 *
 * @author Gregory Gorziza
 */
public class F_Cad_User1 extends javax.swing.JFrame {

    /**
     * Creates new form F_Cadastro_Cliente
     */
    public F_Cad_User1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        bg_documento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        painel_fundo = new javax.swing.JPanel();
        bt_voltar = new javax.swing.JButton();
        painel_container = new javax.swing.JPanel();
        l_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        l_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        l_email = new javax.swing.JLabel();
        txt_senha_confirm = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        bt_salvar = new javax.swing.JButton();

        jColorChooser1.setBackground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        painel_fundo.setBackground(new java.awt.Color(0, 0, 0));
        painel_fundo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel_fundo.setForeground(new java.awt.Color(255, 255, 255));
        painel_fundo.setPreferredSize(new java.awt.Dimension(1280, 720));

        bt_voltar.setBackground(new java.awt.Color(51, 0, 0));
        bt_voltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bt_voltar.setForeground(new java.awt.Color(255, 255, 255));
        bt_voltar.setText("VOLTAR");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });

        painel_container.setBackground(new java.awt.Color(0, 0, 0));
        painel_container.setPreferredSize(new java.awt.Dimension(600, 360));

        l_nome.setBackground(new java.awt.Color(255, 255, 255));
        l_nome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_nome.setForeground(new java.awt.Color(255, 255, 255));
        l_nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_nome.setText("Nome");
        l_nome.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        l_senha.setBackground(new java.awt.Color(255, 255, 255));
        l_senha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_senha.setForeground(new java.awt.Color(255, 255, 255));
        l_senha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_senha.setText("Senha");
        l_senha.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_senha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        l_email.setBackground(new java.awt.Color(255, 255, 255));
        l_email.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_email.setForeground(new java.awt.Color(255, 255, 255));
        l_email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_email.setText("Email");
        l_email.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_senha_confirm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_senha_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senha_confirmActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout painel_containerLayout = new javax.swing.GroupLayout(painel_container);
        painel_container.setLayout(painel_containerLayout);
        painel_containerLayout.setHorizontalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_nome)
            .addComponent(txt_email)
            .addComponent(txt_senha)
            .addComponent(txt_senha_confirm)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_containerLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(312, 312, 312))
            .addGroup(painel_containerLayout.createSequentialGroup()
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_nome)
                    .addComponent(l_email)
                    .addComponent(l_senha))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painel_containerLayout.setVerticalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(txt_senha_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24))
        );

        bt_salvar.setBackground(new java.awt.Color(51, 0, 0));
        bt_salvar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt_salvar.setForeground(new java.awt.Color(255, 255, 255));
        bt_salvar.setText("SALVAR");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_fundoLayout = new javax.swing.GroupLayout(painel_fundo);
        painel_fundo.setLayout(painel_fundoLayout);
        painel_fundoLayout.setHorizontalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_fundoLayout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(painel_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 338, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_fundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(painel_fundoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bt_voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_fundoLayout.setVerticalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_fundoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bt_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(painel_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(bt_salvar)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1296, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        // TODO add your handling code here:
        F_Login l = new F_Login();
        this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        try {  
            String email = txt_email.getText();
            String senha = txt_senha.getText();
            String senhaConfirm = txt_senha_confirm.getText();
            String nome = txt_nome.getText();

            
            if (nome.trim().isEmpty()) {
                mostrarMensagem("O nome não pode estar vazio!");
                return;
            }

            if (!isEmailValido(email)) {
                mostrarMensagem("Email inválido!");
                return;
            }

            if (!isSenhaValida(senha, senhaConfirm)) {
                return; // add mensagem
            }
            

            // Registra user
            Cad c = new Cad();
            c.cadUser(nome,email, senha);
            
            // fecha janela
            F_Login l = new F_Login();
            this.dispose();
            l.setVisible(true);

        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void txt_senha_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senha_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senha_confirmActionPerformed

    private boolean isEmailValido(String email) {
        return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }

    private boolean isSenhaValida(String senha, String senhaConfirm) {
        if (senha.length() < 6 || senhaConfirm.length() < 6) {
            mostrarMensagem("A senha deve ter mais 6 caracteres!");
            return false;
        }
        if (!senha.equals(senhaConfirm)) {
            mostrarMensagem("As senhas não coincidem!");
            return false;
        }
        return true;
    }

    private int isCertificacaoValida(int certificacao) {
        if (certificacao == 3){
            return 0;
        }else{
            return 1;
        }
    }
    
    private int isIntereces(int viagens, int musica, int gastronomia, int livros, int esportes, int natureza, int artes, int jogos, int animais, int causa) {
        int aux = 0;
        if (viagens == 1){
            aux++;
        }
        if (musica == 1){
            aux++;
        }
        if (gastronomia == 1){
            aux++;
        }
        if (livros== 1){
            aux++;
        }
        if (esportes == 1){
            aux++;
        }
        if (natureza == 1){
            aux++;
        }
        if (artes == 1){
            aux++;
        }
        if (jogos == 1){
            aux++;
        }
        if (animais == 1){
            aux++;
        }
        if (causa == 1){
            aux++;
        }
        if (aux >= 3){
            return 1;
        }else{
            return 0;
        }
    }

    private void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Cad_User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Cad_User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Cad_User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Cad_User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Cad_User1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_documento;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_nome;
    private javax.swing.JLabel l_senha;
    private javax.swing.JPanel painel_container;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_senha_confirm;
    // End of variables declaration//GEN-END:variables
}
