package Layout;

//import Algoritimo.Escolhas;

/**
 *
 * @author GregoryGorzizadosSan
 */
public class F_Home extends javax.swing.JFrame {
    /**
     * Creates new form F_Cadastro_Cliente
     */
    
    public F_Home() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        bg_documento = new javax.swing.ButtonGroup();
        painel_fundo1 = new javax.swing.JPanel();
        painel_container2 = new javax.swing.JPanel();
        imagem_list1 = new javax.swing.JLabel();
        painel_container3 = new javax.swing.JPanel();
        b_home = new javax.swing.JButton();
        b_encontro = new javax.swing.JButton();
        b_perfil = new javax.swing.JButton();

        jColorChooser1.setBackground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        painel_fundo1.setBackground(new java.awt.Color(0, 0, 0));
        painel_fundo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel_fundo1.setForeground(new java.awt.Color(255, 255, 255));
        painel_fundo1.setPreferredSize(new java.awt.Dimension(1280, 720));

        painel_container2.setBackground(new java.awt.Color(0, 0, 0));
        painel_container2.setPreferredSize(new java.awt.Dimension(1280, 550));

        imagem_list1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        imagem_list1.setForeground(new java.awt.Color(255, 255, 255));
        imagem_list1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel_container2Layout = new javax.swing.GroupLayout(painel_container2);
        painel_container2.setLayout(painel_container2Layout);
        painel_container2Layout.setHorizontalGroup(
            painel_container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagem_list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel_container2Layout.setVerticalGroup(
            painel_container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_container2Layout.createSequentialGroup()
                .addComponent(imagem_list1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painel_container3.setBackground(new java.awt.Color(0, 0, 0));
        painel_container3.setPreferredSize(new java.awt.Dimension(1280, 60));

        b_home.setBackground(new java.awt.Color(0, 0, 0));
        b_home.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        b_home.setForeground(new java.awt.Color(255, 255, 255));
        b_home.setText("ENCONTRO");
        b_home.setBorder(null);
        b_home.setPreferredSize(new java.awt.Dimension(425, 60));
        b_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_homeActionPerformed(evt);
            }
        });

        b_encontro.setBackground(new java.awt.Color(0, 0, 0));
        b_encontro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        b_encontro.setForeground(new java.awt.Color(255, 255, 255));
        b_encontro.setText("SAIR");
        b_encontro.setBorder(null);
        b_encontro.setPreferredSize(new java.awt.Dimension(425, 60));
        b_encontro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_encontroActionPerformed(evt);
            }
        });

        b_perfil.setBackground(new java.awt.Color(0, 0, 0));
        b_perfil.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        b_perfil.setForeground(new java.awt.Color(255, 255, 255));
        b_perfil.setText("PERFIL");
        b_perfil.setBorder(null);
        b_perfil.setPreferredSize(new java.awt.Dimension(425, 60));
        b_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_perfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_container3Layout = new javax.swing.GroupLayout(painel_container3);
        painel_container3.setLayout(painel_container3Layout);
        painel_container3Layout.setHorizontalGroup(
            painel_container3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_container3Layout.createSequentialGroup()
                .addComponent(b_encontro, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_home, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(b_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painel_container3Layout.setVerticalGroup(
            painel_container3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_container3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_encontro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painel_fundo1Layout = new javax.swing.GroupLayout(painel_fundo1);
        painel_fundo1.setLayout(painel_fundo1Layout);
        painel_fundo1Layout.setHorizontalGroup(
            painel_fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_container3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1274, Short.MAX_VALUE)
            .addGroup(painel_fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_fundo1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painel_container2, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painel_fundo1Layout.setVerticalGroup(
            painel_fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_fundo1Layout.createSequentialGroup()
                .addGap(0, 654, Short.MAX_VALUE)
                .addComponent(painel_container3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painel_fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_fundo1Layout.createSequentialGroup()
                    .addComponent(painel_container2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 226, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_fundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_fundo1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 1296, 728);
    }// </editor-fold>//GEN-END:initComponents
 
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        /*
        Escolhas u = new Escolhas();

        switch (evt.getKeyCode()) {    
            case KeyEvent.VK_UP:
                System.out.println("Seta para cima pressionada");
                // passa
                break;
//            case KeyEvent.VK_DOWN:
//                System.out.println("Seta para baixo pressionada");
//                // volta
//                break;
            case KeyEvent.VK_LEFT:
                System.out.println("Seta para esquerda pressionada");
                // gostei
                this.gostei = 1;
                break;
            case KeyEvent.VK_RIGHT:
                System.out.println("Seta para direita pressionada");
                // amei
                this.amei = 1;
                break;
            default:
                break;
        }
        String[] dados = u.passa(this.id, this.atracao, this.nome, this.gostei, this.amei); // Call passa method
        try {
            this.id = Integer.parseInt(dados[0]);
            System.out.println(this.id);
            this.atracao = Integer.parseInt(dados[1]);
            System.out.println(this.atracao);
            this.nome = dados[2];
            System.out.println(this.nome);
            this.gostei = Integer.parseInt(dados[3]);
            System.out.println(this.gostei);
            this.amei = Integer.parseInt(dados[4]);
            System.out.println(this.amei);

        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter dados: " + e.getMessage());
            // Handle the error as appropriate
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Dados retornados não possuem o número esperado de elementos.");
            F_Login v = new F_Login();
            this.dispose();
            v.setVisible(true);
            // Handle the error as appropriate
        }
        imagem_list.setText(this.nome); // Update the UI with the name
        */
    }//GEN-LAST:event_formKeyPressed

    private void b_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_homeActionPerformed

    private void b_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_perfilActionPerformed
        // TODO add your handling code here:
        F_Perfil p = new F_Perfil();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_b_perfilActionPerformed

    private void b_encontroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_encontroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_encontroActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_encontro;
    private javax.swing.JButton b_home;
    private javax.swing.JButton b_perfil;
    private javax.swing.ButtonGroup bg_documento;
    private javax.swing.JLabel imagem_list1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel painel_container2;
    private javax.swing.JPanel painel_container3;
    private javax.swing.JPanel painel_fundo1;
    // End of variables declaration//GEN-END:variables
}
