package Layout;

import Banco.Conect;
import User.Del;
import User.Edit;
import User.User;
import User.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author GregoryGorzizadosSan
 */
public class F_Perfil extends javax.swing.JFrame {
    int id;
    /**
     * Creates new form F_Cadastro_Cliente
     */
    public F_Perfil() {
        initComponents();
        carregar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        bg_documento = new javax.swing.ButtonGroup();
        painel_fundo = new javax.swing.JPanel();
        painel_container = new javax.swing.JPanel();
        l_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        l_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        l_email = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        bt_excluir = new javax.swing.JButton();
        l_preferencias1 = new javax.swing.JLabel();
        bt_volta = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();

        jColorChooser1.setBackground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel_fundo.setBackground(new java.awt.Color(0, 0, 0));
        painel_fundo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel_fundo.setForeground(new java.awt.Color(255, 255, 255));
        painel_fundo.setPreferredSize(new java.awt.Dimension(1280, 720));

        painel_container.setBackground(new java.awt.Color(0, 0, 0));
        painel_container.setPreferredSize(new java.awt.Dimension(600, 300));

        l_nome.setBackground(new java.awt.Color(255, 255, 255));
        l_nome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_nome.setForeground(new java.awt.Color(255, 255, 255));
        l_nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_nome.setText("Nome");
        l_nome.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        l_senha.setBackground(new java.awt.Color(255, 255, 255));
        l_senha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_senha.setForeground(new java.awt.Color(255, 255, 255));
        l_senha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_senha.setText("Senha");
        l_senha.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_senha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        l_email.setBackground(new java.awt.Color(255, 255, 255));
        l_email.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_email.setForeground(new java.awt.Color(255, 255, 255));
        l_email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_email.setText("Email");
        l_email.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout painel_containerLayout = new javax.swing.GroupLayout(painel_container);
        painel_container.setLayout(painel_containerLayout);
        painel_containerLayout.setHorizontalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_nome)
            .addComponent(txt_email)
            .addComponent(txt_senha)
            .addGroup(painel_containerLayout.createSequentialGroup()
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_nome)
                    .addComponent(l_email)
                    .addComponent(l_senha))
                .addContainerGap(527, Short.MAX_VALUE))
            .addGroup(painel_containerLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painel_containerLayout.setVerticalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel24))
        );

        bt_excluir.setBackground(new java.awt.Color(51, 0, 0));
        bt_excluir.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt_excluir.setForeground(new java.awt.Color(255, 255, 255));
        bt_excluir.setText("Excluir");
        bt_excluir.setPreferredSize(new java.awt.Dimension(213, 71));
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        l_preferencias1.setBackground(new java.awt.Color(255, 255, 255));
        l_preferencias1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l_preferencias1.setForeground(new java.awt.Color(255, 255, 255));
        l_preferencias1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_preferencias1.setText("Perfil");
        l_preferencias1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bt_volta.setBackground(new java.awt.Color(51, 0, 0));
        bt_volta.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt_volta.setForeground(new java.awt.Color(255, 255, 255));
        bt_volta.setText("Voltar");
        bt_volta.setPreferredSize(new java.awt.Dimension(213, 71));
        bt_volta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltaActionPerformed(evt);
            }
        });

        bt_editar.setBackground(new java.awt.Color(51, 0, 0));
        bt_editar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt_editar.setForeground(new java.awt.Color(255, 255, 255));
        bt_editar.setText("Editar");
        bt_editar.setPreferredSize(new java.awt.Dimension(213, 71));
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_fundoLayout = new javax.swing.GroupLayout(painel_fundo);
        painel_fundo.setLayout(painel_fundoLayout);
        painel_fundoLayout.setHorizontalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_fundoLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(painel_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(painel_fundoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_fundoLayout.createSequentialGroup()
                        .addComponent(bt_volta, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painel_fundoLayout.createSequentialGroup()
                        .addComponent(l_preferencias1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_fundoLayout.createSequentialGroup()
                    .addContainerGap(944, Short.MAX_VALUE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );
        painel_fundoLayout.setVerticalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_fundoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_preferencias1)
                    .addComponent(bt_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(painel_container, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(bt_volta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_fundoLayout.createSequentialGroup()
                    .addContainerGap(613, Short.MAX_VALUE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1296, 728);
    }// </editor-fold>//GEN-END:initComponents
   
    private void carregar() {
        // Obtém o usuário da sessão em vez de criar um novo
        User u = UserSession.getInstance().getCurrentUser();
        if (u == null) {
            System.out.println("Nenhum usuário logado!");
            return;
        }

        this.id = u.getId(); // Agora pega o ID correto

        String sql = "SELECT email, nome, senha FROM user WHERE id = ?";
        try (Connection conn = Conect.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                txt_email.setText(rs.getString("email"));
                txt_senha.setText(rs.getString("senha"));
                txt_nome.setText(rs.getString("nome"));
            } else {
                System.out.println("Usuário não encontrado no BD.");
            }
        } catch (SQLException e) {
            System.out.println("Erro SQL: " + e.getMessage());
        }
    }
    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        Del d = new Del();
        d.DelUser(this.id);
        
        F_Login h = new F_Login();
        this.dispose();
        h.setVisible(true);
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_voltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltaActionPerformed
        F_Home h = new F_Home();
        this.dispose();
        h.setVisible(true);
    }//GEN-LAST:event_bt_voltaActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        try {  
            String email = txt_email.getText();
            String senha = txt_senha.getText();
            String nome = txt_nome.getText();

            if (nome.trim().isEmpty()) {
                mostrarMensagem("O nome não pode estar vazio!");
                return;
            }

            if (!isEmailValido(email)) {
                mostrarMensagem("Email inválido!");
                return;
            }
            
            // Registra user
            Edit e = new Edit();
            e.EditUser(this.id,nome,email, senha);
            
            // fecha janela
            mostrarMensagem("Edição Salva!");

        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private boolean isEmailValido(String email) {
        return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }

    private boolean isSenhaValida(String senha, String senhaConfirm) {
        if (senha.length() < 6 || senhaConfirm.length() < 6) {
            mostrarMensagem("A senha deve ter no minimo 6 caracteres!");
            return false;
        }
        if (!senha.equals(senhaConfirm)) {
            mostrarMensagem("As senhas não coincidem!");
            return false;
        }
        return true;
    }

    private int isCertificacaoValida(int certificacao) {
        if (certificacao == 3){
            return 0;
        }else{
            return 1;
        }
    }

    private void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_documento;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_volta;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_nome;
    private javax.swing.JLabel l_preferencias1;
    private javax.swing.JLabel l_senha;
    private javax.swing.JPanel painel_container;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_senha;
    // End of variables declaration//GEN-END:variables
}
